In [1]:
f = @(x) sin(x);
x = linspace(0, 2*pi, 5);
n = length(x);

In [2]:
divided_differences(f,x)


A =

         0         0         0         0         0
    1.0000    0.6366         0         0         0
    0.0000   -0.6366   -0.4053         0         0
   -1.0000   -0.6366   -0.0000    0.0860         0
   -0.0000    0.6366    0.4053    0.0860    0.0000


ans =

         0         0         0         0         0
    1.0000    0.6366         0         0         0
    0.0000   -0.6366   -0.4053         0         0
   -1.0000   -0.6366   -0.0000    0.0860         0
   -0.0000    0.6366    0.4053    0.0860    0.0000



3.a

In [10]:
x


x =

   -3.1416   -1.5708    1.5708    3.1416



In [11]:
m = zeros(n,n)


m =

     0     0     0     0
     0     0     0     0
     0     0     0     0
     0     0     0     0



In [12]:
% j = spalte i = zeile
%erste spalte
for j = 1:n
    m(j,1) = f(x(j))
end


m =

   1.0e-15 *

   -0.1225         0         0         0
         0         0         0         0
         0         0         0         0
         0         0         0         0


m =

   -0.0000         0         0         0
   -1.0000         0         0         0
         0         0         0         0
         0         0         0         0


m =

   -0.0000         0         0         0
   -1.0000         0         0         0
    1.0000         0         0         0
         0         0         0         0


m =

   -0.0000         0         0         0
   -1.0000         0         0         0
    1.0000         0         0         0
    0.0000         0         0         0



In [13]:
% j = spalte i = zeile
for i = 2:n
    for j = 2:i
        i
        j
        k = abs(i-j)
        m(i,j) = (m(i,j-1) - m(i-1,j-1)) / (x(i) - x(k+1))
    end
end


i =

     2


j =

     2


k =

     0


m =

   -0.0000         0         0         0
   -1.0000   -0.6366         0         0
    1.0000         0         0         0
    0.0000         0         0         0


i =

     3


j =

     2


k =

     1


m =

   -0.0000         0         0         0
   -1.0000   -0.6366         0         0
    1.0000    0.6366         0         0
    0.0000         0         0         0


i =

     3


j =

     3


k =

     0


m =

   -0.0000         0         0         0
   -1.0000   -0.6366         0         0
    1.0000    0.6366    0.2702         0
    0.0000         0         0         0


i =

     4


j =

     2


k =

     2


m =

   -0.0000         0         0         0
   -1.0000   -0.6366         0         0
    1.0000    0.6366    0.2702         0
    0.0000   -0.6366         0         0


i =

     4


j =

     3


k =

     1


m =

   -0.0000         0         0         0
   -1.0000   -0.6366         0         0
    1.0000    0.63

In [14]:
m


m =

   -0.0000         0         0         0
   -1.0000   -0.6366         0         0
    1.0000    0.6366    0.2702         0
    0.0000   -0.6366   -0.2702   -0.0860



3b

In [14]:
a = [ 0 -2/pi 8/(3*pi^2) -8/(3*pi^3)]
x = [ -pi -pi/2 pi/2 pi]
y = 3*pi/2


a =

         0   -0.6366    0.2702   -0.0860


x =

   -3.1416   -1.5708    1.5708    3.1416


y =

    4.7124



In [ ]:
function y = horner(x,p)
%
% Auswertung eines Polynom an einer Stelle mithilfe Horner Schema
%
    [one,coeffs] = size(p);
    if coeffs == 1
	result = p(coeffs)
    else
    	result = p(1) + x*hornerschema(x,p(2:coeffs));
    end

    y = result
end


In [15]:
horner_eval(a,x,y)

Error using eval
Undefined function 'horner_eval' for input arguments of type 'double'.



In [3]:
% 3c

In [4]:
f = @(x) cos(x);
x = linspace(0, 2*pi, 5);

In [5]:
a = divided_differences(f,x)


A =

    1.0000         0         0         0         0
    0.0000   -0.6366         0         0         0
   -1.0000   -0.6366   -0.0000         0         0
   -0.0000    0.6366    0.4053    0.0860         0
    1.0000    0.6366    0.0000   -0.0860   -0.0274


a =

    1.0000         0         0         0         0
    0.0000   -0.6366         0         0         0
   -1.0000   -0.6366   -0.0000         0         0
   -0.0000    0.6366    0.4053    0.0860         0
    1.0000    0.6366    0.0000   -0.0860   -0.0274

